### ISSUE TITLE
> 环境：python3.6  请问这是要改什么配置，我的python3.6  在pycharm中也改了文件编码格式utf-8   还是报这个

### ISSUE THREAD

**Issue by renjunyou** [SeldomQA/XTestRunner#13]
> 环境：python3.6
> 根据他的书来
> 反正没安装成功
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 1750-1753: ordinal not in range(128)

你的这个应该是因为没改配置

_Originally posted by @5shuai in https://github.com/SeldomQA/HTMLTestRunner/issues/5#issuecomment-750812584_

**Comment by JoeEmp** [comment]
使用命令行python3安装还是会报该错误的。去掉mail.html 和 template.html才成功安装。
