### ISSUE TITLE
用“seldom -h2c“生成的测试用例，执行XTestRunner报错，count没统计到。如图

### ISSUE THREAD

**Issue by Silence0789** [SeldomQA/XTestRunner#17]
![image](https://user-images.githubusercontent.com/35662458/161586813-ede6bb32-c19e-4b82-9ce9-a0584d0b9a4b.png)

![image](https://user-images.githubusercontent.com/35662458/161587178-611733f2-cf5e-4c2a-83e7-7b0d651eede8.png)

**Comment by defnngj** [comment]
编写的用例不符合 unittest 定义用例的规则（用例必须以`test` 开头），导致计算用例总数为 0 。引起的异常。

**Comment by defnngj** [comment]
`v 1.4.0` 版本已修复。

**Comment by Silence0789** [comment]
了解了，我以后注意下，感谢修复。
