### ISSUE TITLE
unittest中的subTest()方法导致失败的case未被捕捉到

### ISSUE THREAD

**Issue by 360kevin** [SeldomQA/XTestRunner#18]
目前采用python3.9用subTest()保证失败的case可以继续执行，导致目前用xtestrunner的时候无法识别fail的case，只有成功的case会被捕捉，什么时候考虑支持一下？

**Comment by defnngj** [comment]
非常感谢你的建议~！`version 1.4.1` 版本增加了对 `subTest()` 的支持

**Comment by 360kevin** [comment]
确认可以统计，1.4.1版本；

另外发现支持subTest()方法后，报告中pass的case多统计了1个case，计算应该循环12个case，测试报告是13个case，没看出来为啥多了，整体fail的case数量没有问题，符合预期，pass的多了；

**Comment by defnngj** [comment]
官方交流QQ群：948994709    更快捷的交流问题。
