### ISSUE TITLE
跳过用例时，报告中无法隐藏用例

### ISSUE THREAD

**Issue by tcbga** [SeldomQA/XTestRunner#24]
跳过用例时，报告中无法隐藏用例，count需要加上num_skip
![image](https://user-images.githubusercontent.com/110442661/182289388-11cf0ac4-20ad-4633-8635-b7e70091fd23.png)
![image](https://user-images.githubusercontent.com/110442661/182289448-34d4eabe-bb1d-4e9e-89c3-cefcb5a0cc06.png)

**Comment by defnngj** [comment]
问题已修复！
