### ISSUE TITLE
近期的修改报 No module named 'XTestRunner'

### ISSUE THREAD

**Issue by huangjiafengx** [SeldomQA/XTestRunner#36]
明明已经安装XTestRunner成功，在python中却显示No module named 'XTestRunner'

![image](https://user-images.githubusercontent.com/92708152/223958726-abc902bc-f0c4-4e8b-9e2d-cdaf9f9a83a0.png)

![image](https://user-images.githubusercontent.com/92708152/223959080-2d735d55-739e-4064-9b91-2d1248ef19b4.png)

该问题可能是3天内引入的。
![image](https://user-images.githubusercontent.com/92708152/223958382-8e088a47-3918-4216-9e8a-1b5e3f1472c3.png)

**Comment by duanwq666** [comment]
> 明明已经安装XTestRunner成功，在python中却显示No module named 'XTestRunner'
> 
> ![图像](https://user-images.githubusercontent.com/92708152/223958726-abc902bc-f0c4-4e8b-9e2d-cdaf9f9a83a0.png)
> 
> ![图像](https://user-images.githubusercontent.com/92708152/223959080-2d735d55-739e-4064-9b91-2d1248ef19b4.png)
> 
> 该问题可能是三天内引入的。 ![图像](https://user-images.githubusercontent.com/92708152/223958382-8e088a47-3918-4216-9e8a-1b5e3f1472c3.png)

有解决吗

**Comment by harpyestar** [comment]
pip install xtestrunner==1.5.0
pip install jinja2==3.1.2

降级安装之前的，就好了，请楼主新版本待修复一下这个问题！

**Comment by duanwq666** [comment]
> 

1.5的虽然没有上面的错但是不会生成测试报告

**Comment by duanwq666** [comment]
> pip 安装 xtestrunner==1.5.0 pip 安装 jinja2==3.1.2
> 
> 降级安装之前的，就好了，请楼主新版待修复一下这个问题！

没有报错也没有生成测试报告

**Comment by defnngj** [comment]
关于 jinja2 版本依赖的问题 已经紧急发布了 `XTestRunner == 1.6.1` 解决。

如果是 seldom 使用 XTestRunenr 导致的问题，请暂时 退回  `XTestRunner == 1.5.0`， 我会尽快发布 seldom 版本，已便于支持最新的  `XTestRunner == 1.6.1`。
