### ISSUE TITLE
输出的测试报告统计结果错误

### ISSUE THREAD

**Issue by ZengQingci** [SeldomQA/XTestRunner#39]
![image](https://user-images.githubusercontent.com/48540101/234200460-f293429a-3b60-4cdc-9512-f7a8b05a3853.png)
这个失败和错误统计对应不上

**Comment by defnngj** [comment]
@ZengQingci  提供一下 XTestRunner版本，这个问题在最新版本里已经修复了。

**Comment by ZengQingci** [comment]
1.5.0

**Comment by ZengQingci** [comment]
> @ZengQingci 提供一下 XTestRunner版本，这个问题在最新版本里已经修复了。
