### ISSUE TITLE
报告截图的一些问题和尝试

### ISSUE THREAD

**Issue by ssfanli** [SeldomQA/XTestRunner#4]
# 现象

前段时间用你没重构前的报告框架，在截图这块也尝试过在addError/addFailure方法中增加截图逻辑，这样业务层代码确实不需要再额外添加截图逻辑，但有一个问题：如果有tearDown逻辑，截图会在tearDown逻辑之后执行，会改变报错场景，得到无效的截图

# 解决方案

目前我这边最开始尝试的解决方案是重写unittest常用的断言方法，增加失败截图的逻辑，这样在fail的时候就会截到当时的图片；
但这样还存在一个问题：当case error时依然没法截到当时的图，最终的解决方案是在case层增加一层截图的装饰器

**Comment by defnngj** [comment]
欢迎将你的方案贡献出来， 提交PR。

**Comment by BonaNing** [comment]
请问工程中的测试报告截图需要怎样使用呢？目前测试报告中输出的各种测试用例 截图那一栏 都是“无截图”

**Comment by ssfanli** [comment]
> 请问工程中的测试报告截图需要怎样使用呢？目前测试报告中输出的各种测试用例 截图那一栏 都是“无截图”

截图，把图片用base64编码，然后append到imgs列表里面
p.s. imgs是HTMLTestRunner里面的存储图片的变量

**Comment by ssfanli** [comment]
> 欢迎将你的方案贡献出来， 提交PR。

感谢，不过只是解决方案，没法pr～
