### ISSUE TITLE
参数化接口自动化测试时，如何给执行的每个测试用例加上描述？

### ISSUE THREAD

**Issue by xuanchangxian** [SeldomQA/XTestRunner#48]
![image](https://github.com/SeldomQA/XTestRunner/assets/10562320/a6f77390-a31f-4468-9d5d-7419af42d1d5)

![image](https://github.com/SeldomQA/XTestRunner/assets/10562320/c9068467-edba-41e9-82cf-9ed21f2a6c1d)

**Comment by defnngj** [comment]
@xuanchangxian  这的 ddt 的问题，他联支持，你可以可以使用 seldom 的数据驱动，可以很好的支持。

![image](https://github.com/SeldomQA/XTestRunner/assets/1000588/ebfa6f21-7ab4-42ed-9cec-7acb87279599)

默认将第一列的数据作为`用例描述`。

支持各种数据文件。参考：https://seldomqa.github.io/getting-started/data_driver.html

**Comment by xuanchangxian** [comment]
明白了，多谢🙏
