### ISSUE TITLE
希望能加上去掉报告底部脚注的参数

### ISSUE THREAD

**Issue by yihanglee-cn** [SeldomQA/XTestRunner#49]
在公司使用本模块生成的报告，底部都会自动加上脚注，个人觉得有影响（跟公司品牌互斥）。虽然说可以手动在模板中去掉，但是不可能每次都手动去修改。如果本项目是开源的话，我建议可以去掉脚注或者给可以去掉脚注的参数。

**Comment by defnngj** [comment]
@yihanglee-cn  升级到 `1.7.4` 版本，页脚去掉了`重定向科技`字样， 修改为 `SeldomQA Team` ，如果这都不允许保留，无疑有 __白嫖__ 嫌疑。

请保持对开源项目的尊重。
