### ISSUE TITLE
按照你的配置，使用demo，生成不了html文档

### ISSUE THREAD

**Issue by 5shuai** [SeldomQA/XTestRunner#5]
环境：python3.7
问题：
安装了版本，也用了你的demo，就是生成不了html
麻烦指点下！

**Comment by p112823** [comment]
环境：python3.6
根据他的书来
反正没安装成功
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1750-1753: ordinal not in range(128)

**Comment by 5shuai** [comment]
> 环境：python3.6
> 根据他的书来
> 反正没安装成功
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 1750-1753: ordinal not in range(128)

你的这个应该是因为没改配置

**Comment by p112823** [comment]
搞定了

**Comment by d635747247** [comment]
为什么在家里的电脑生成的是好的，在公司的电脑上报告页面就展示不全了，一样的配置

**Comment by JNULYD** [comment]
同样遇到这个问题。 pycharm中设置 file encodings 的编码为 utf8可以解决。这个设置也可以解决大多数编码问题
