### ISSUE TITLE
希望能展示 `subtest.msg` 而不是 `subtest.shortDescription`

### ISSUE THREAD

**Issue by Morriaty-The-Murderer** [SeldomQA/XTestRunner#51]
```python3
class TestOdd(unittest.TestCase):
    def test_odd(self):
        """
        check if odd
        """
        for i in range(0, 5):
            with self.subTest(f"checking {i}", i=i):
                self.assertTrue(i % 2)
```

现在html里展示的是：

Test Group/Test Case | Description
-- | --
test_odd | check if odd
test_odd | check if odd
test_odd | check if odd
test_odd | check if odd
test_odd | check if odd

希望展示的：
Test Group/Test Case | Description
-- | --
test_odd | checking 0
test_odd | checking 1
test_odd | checking 2
test_odd | checking 3
test_odd | checking 4

我有试着直接去改，但直接判断 `isinstance(test, unittest.case._SubTest)` 没有效果
```python3
# XTestRunner/XTestRunner/htmlrunner/runner.py:line 431
doc = str(test) if isinstance(test, unittest.case._SubTest) else test.shortDescription() or ""
```

**Comment by defnngj** [comment]
@Morriaty-The-Murderer 

已经支持了，请升级 `1.7.5` 版本

用法上略有不同，这里使用的自定义参数`desc=` ，避免和 msg 有冲突，代码中也好区分。

```py
class MyTest(unittest.TestCase):

    def test_even(self):
        """
        Test that numbers between 0 and 5 are all even.
        """
        for i in range(0, 6):
            with self.subTest(desc=f"checking {i}", i=i):
                self.assertEqual(i % 2, 0)

```

报告展示效果：
![image](https://github.com/user-attachments/assets/b6ffe1b4-f5d9-47ab-9eb0-2219d8f48c15)
