### ISSUE TITLE
报告结果调整。

### ISSUE THREAD

**Issue by liyangzbx** [SeldomQA/XTestRunner#53]
你好，请问下，我这边想做两处调整，该如何实现。如下图：
![image](https://github.com/user-attachments/assets/25a354f9-f5ea-4c22-a310-e2db61e8e7bf)

一是这些表头的“测试类/测试用例”这些中文字体显示感觉有点小，如何调整？
二是测试结果通过与否，这个线条可否改成文字的“通过”，“失败”等。在何处能修改？
谢谢！

**Comment by defnngj** [comment]
@liyangzbx  升级 `XTestRunner == 1.7.6` 版本。 

已做了优化，如下图：

![image](https://github.com/user-attachments/assets/a91de63d-8f9c-46d8-8b20-f5854dbf958d)
